insert into medicine_stock values (1, 'disaccharide gentiobiose, dicarboxylic acid crocetin', '2022-09-12', 'Crocin', 200, 'Apollo Pharmacy', 'General');
insert into medicine_stock values (2, 'Cardenolide glycosides, derivatives', '2023-09-12', 'Digoxin', 300, 'Group Pharmacy', 'Cardiology');
insert into medicine_stock values (3, 'miscellaneous GI agents', '2021-09-12', 'Ascoril', 1000, 'Amie Pharmacy', 'Gynaecology');
insert into medicine_stock values (4, 'Colloidal silicon dioxide, croscarmellose sodium, crospovidone, microcrystalline cellulose', '2021-09-12', 'Panif', 500, 'Shaziya Pharmacy', 'Orthopaedics');
insert into medicine_stock values (5, 'oxycodone, Dihydrohydroxycodeinone, Dihydrone, Oxycodeinone', '2024-09-12', 'Nexpro', 600, 'Apollo Pharmacy', 'Orthopaedics');
insert into medicine_stock values (6, 'Dusparsha, Eranda, Manjishta, Chithrakam', '2023-09-12', 'Orthoherb', 800, 'Group Pharmacy', 'Orthopaedics');
insert into medicine_stock values (7, 'ergocalciferol-D2, cholecalciferol-D3, alfacalcidol', '2023-09-03', 'Cholecalciferol', 300, 'Amie Pharmacy', 'Orthopaedics');
insert into medicine_stock values (8, 'sodium alginate 250 mg, sodium hydrogen carbonate 133.5 mg and calcium carbonate 80 mg', '2022-09-12', 'Vitamin-c', 500, 'Medlife Pharmacy', 'General');
insert into medicine_stock values (9, 'Paracetamol , Acetaminophen', '2023-07-12', 'Dolo-650', 500, 'Apollo Pharmacy', 'General');
insert into medicine_stock values (10, 'Cephradine , Cephalosporin', '2024-08-11', 'Hilact', 600, 'Medlife Pharmacy', 'Gynaecology');
insert into medicine_stock values (11, 'Dicycloverine, Dicyclomine+Paracetamol, Acetaminophen', '2022-08-11', 'Cyclopam', 300, 'Sun Pharmacy', 'Gynaecology');